# Generated by Django 5.1.5 on 2025-01-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('fase1', 'Fase 1'), ('fase2', 'Fase 2'), ('fase3', 'Fase 3'), ('fase4', 'Fase 4')], default='fase1', max_length=50)),
            ],
        ),
    ]
